services:
  db:
    image: mysql:lts
    container_name: fiap_erp_mysql
    restart: unless-stopped
    ports:
      - "3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: "host.docker.internal"
      MYSQL_DATABASE: "erp_restaurant"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: America/Sao_Paulo
    networks:
      - fiap_erp
  app:
    image: fiap_erp_app
    container_name: fiap_erp_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/erp_restaurant
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: "466238"
    networks:
      - fiap_erp
volumes:
  mysql_data:
    driver: local

networks:
  fiap_erp:
    driver: bridge