version: '3.8'
services:
  db:
    image: meu-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: minha_aplicacao
      MYSQL_PASSWORD: minha_senha
    volumes:
      - db_data:/var/lib/mysql
  app:
    image: minha-app
    ports:
      - "8080:8080"
    environment:
      MYSQL_USER: minha_aplicacao
      MYSQL_PASSWORD: minha_senha
    depends_on:
      - db