services:
  app:
    image: fiap_erp_app
    container_name: fiap_erp_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
  db:
    image: mysql:lts
    container_name: fiap_erp_mysql
    restart: unless-stopped
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "erp_restaurant"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: America/Sao_Paulo

volumes:
  mysql_data:
    driver: local

networks:
  fiap_erp:
    driver: bridge