services:
  app:
    image: fiap_erp_app
    container_name: fiap_erp_app
    restart: unless-stopped
    ports:
      - "${FORWARD_APP_PORT:-8080}:8080"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    depends_on:
      - db
    networks:
      fiap_erp:
        ipv4_address: 10.10.0.2
  db:
    image: mysql:lts
    container_name: fiap_erp_mysql
    restart: unless-stopped
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: America/Sao_Paulo
    networks:
      fiap_erp:
        ipv4_address: 10.10.0.3

volumes:
  mysql_data:
    driver: local

networks:
  fiap_erp:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
